# generic
permalink: 'pretty'
highlighter: 'pygments'
exclude: ['Gemfile', 'Gemfile.lock', 'start-server', 'README.md']

# custom, required
author: 'David Brinegar'
url: 'https://dbrinegar.github.io'

# custom, optional
email:
google_analytics_account: 'UA-57632919-1'
github_account: 'dbrinegar'
disqus_account: 'dbrinegar'
twitter_account: 'davidbrinegar'
twitter_widget_id: '287276808276152320'
