# generic
permalink: 'pretty'
highlighter: true
exclude: ['Gemfile', 'Gemfile.lock', 'start-server']

# custom
author: 'David Brinegar'
email:
url: 'https://dbrinegar.github.io'
google_analytics_account: 'UA-57632919-1'
github_account: 'dbrinegar'
disqus_account: 'dbrinegar'
twitter_account: 'davidbrinegar'
twitter_widget_id: '287276808276152320'
